include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [
      "build/**",
      ".dart_tool/**",
      "**/*.g.dart",
      "**/*.freezed.dart",
      "lib/gen/**",
      "**/*.mocks.dart",
      "lib/generated_plugin_registrant.dart"
  ]
  strong-mode:
    implicit-casts: true

  errors:
    unused_import: error
    invalid_annotation_target: ignore

linter:
  rules:
    - annotate_overrides